### ISSUE TITLE
I don't have additional options in response

### ISSUE THREAD

**Issue by damian-balas** [raffaelj/cockpit_ImageResize#1]
my response looks like this: 

```
...
image: {
   path: "/storage/uploads/2020/08/23...."
},
...
```

**Comment by raffaelj** [comment]
@damian-balas I'm sorry, I missed that issue.

I guess, that you used the image field and not the asset field. If I remember correctly, images have only a path key. If you use the asset field instead, the whole asset object is available in your entry.
